-- Tesla Wall Connector EV charging tables, mirrored from the
-- home_monitoring relay over WebSocket (the solar bridge never polls the
-- charger directly). Flat naming per this project's convention.
-- session_id is generated by the home relay; the mirror upserts on it, so
-- reconnect backfill is idempotent. Per-session history is permanent; only
-- the sparse vitals snapshots are pruned by the retention job below.

create extension if not exists "pgcrypto";

-- One row per completed charge session, mirrored at contactor-open.
create table if not exists public.ev_charging_sessions (
  session_id uuid primary key default gen_random_uuid(),
  started_at timestamptz not null,
  ended_at timestamptz not null,
  energy_wh numeric(12, 3) not null default 0,
  duration_s integer not null default 0,
  max_current_a numeric(8, 2),
  avg_grid_v numeric(8, 2),
  max_handle_temp_c numeric(6, 2),
  alerts jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  constraint ev_charging_sessions_chronology check (ended_at >= started_at),
  constraint ev_charging_sessions_energy_nonnegative check (energy_wh >= 0),
  constraint ev_charging_sessions_duration_nonnegative check (duration_s >= 0)
);

create index if not exists ev_charging_sessions_started_at_idx
  on public.ev_charging_sessions (started_at desc);

-- Sparse periodic vitals mirrored from the home relay's ev block.
-- Latest row backs /api/ev/live.
create table if not exists public.ev_vitals_snapshots (
  timestamp timestamptz primary key,
  contactor_closed boolean,
  vehicle_connected boolean,
  session_energy_wh numeric(12, 3),
  vehicle_current_a numeric(8, 2),
  grid_v numeric(8, 2),
  handle_temp_c numeric(6, 2),
  pcba_temp_c numeric(6, 2),
  lifetime_energy_wh numeric(14, 3),
  created_at timestamptz not null default now()
);

create index if not exists ev_vitals_snapshots_timestamp_idx
  on public.ev_vitals_snapshots (timestamp desc);

-- Per-day EV rollup over completed sessions, attributed to the day the
-- session started in the caller's timezone.
create or replace function public.get_ev_daily_summary(
  timezone_name text default 'America/New_York',
  day_limit integer default 30
)
returns table (
  day date,
  session_count bigint,
  ev_kwh numeric,
  charging_seconds bigint
)
language sql
stable
as $$
  select
    (s.started_at at time zone timezone_name)::date as day,
    count(*)::bigint as session_count,
    round(sum(s.energy_wh) / 1000.0, 3) as ev_kwh,
    sum(s.duration_s)::bigint as charging_seconds
  from public.ev_charging_sessions s
  where s.started_at >= now() - make_interval(days => greatest(day_limit, 1))
  group by 1
  order by 1 desc;
$$;

-- Retention: sessions are permanent; prune snapshots older than the window.
create or replace function public.cleanup_ev_vitals_snapshots(
  retention_days integer default 30
)
returns bigint
language sql
as $$
  with deleted as (
    delete from public.ev_vitals_snapshots
    where timestamp < now() - make_interval(days => greatest(retention_days, 1))
    returning 1
  )
  select count(*)::bigint from deleted;
$$;

create extension if not exists pg_cron;

do $$
begin
  perform cron.unschedule('ev-vitals-retention');
exception when others then
  -- Job did not exist yet; safe to ignore.
  null;
end $$;

select cron.schedule(
  'ev-vitals-retention',
  '0 3 * * *',
  'select public.cleanup_ev_vitals_snapshots(30)'
);
